aws_region         = "us-east-1"
ami_id             = "ami-<AWS AMI ID>"
instance_type      = "t3.micro"
subnet_id          = "subnet-<AWS Subnet ID>"
security_group_ids = ["sg-<AWS Security Group>"]
key_name           = "<AWS Key Pair>"
instance_name      = "finwebtech-terraform-linux"
environment        = "dev"
owner              = "alex"
